# Generated by Django 2.1.7 on 2019-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20190306_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='ball_k',
            field=models.IntegerField(null=True, verbose_name='Минимальный балл на контракт'),
        ),
    ]
