# Generated by Django 2.1.7 on 2019-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20190306_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='profile_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Профиль'),
        ),
    ]
