# Generated by Django 2.1.7 on 2019-03-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20190306_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='random_id',
            field=models.IntegerField(default=0, verbose_name='идентификатор сообщений'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_news',
            field=models.CharField(default='null', max_length=100, verbose_name='Последняя новость'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lk_code',
            field=models.IntegerField(default=0, verbose_name='Код личного кабинета'),
        ),
    ]
