# Generated by Django 2.1.7 on 2019-05-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='updated_date',
        ),
    ]
