# Generated by Django 2.1.7 on 2019-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20190510_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='feedback',
            field=models.CharField(default='false', max_length=20, verbose_name='Обратная связь'),
        ),
    ]
