# Generated by Django 2.1.7 on 2019-03-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20190317_1052'),
        ('administrator', '0006_auto_20190317_1048'),
    ]

    operations = [
    ]
