# Generated by Django 2.1.7 on 2019-05-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_account_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='RN',
            field=models.IntegerField(null=True, verbose_name='Приоритет'),
        ),
    ]
