# Generated by Django 2.1.7 on 2020-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_direction_rn'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency_snap_id',
            field=models.IntegerField(default=-1, verbose_name='Текущий снимок'),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lk_code',
            field=models.CharField(default=0, max_length=60, verbose_name='Код личного кабинета'),
        ),
    ]
