# Generated by Django 2.1.7 on 2019-06-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_direction_rn'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency_snap_id',
            field=models.IntegerField(default=-1, verbose_name='Текущий снимок'),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
