# Generated by Django 2.1.7 on 2019-03-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_merge_20190319_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultOfTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightAnswer', models.IntegerField(default=0, verbose_name='Количество правильных ответов')),
                ('allAnswer', models.IntegerField(default=0, verbose_name='Количество всех ответов')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='administrator.Test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты теста',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='tests',
            field=models.ManyToManyField(related_name='account', to='administrator.ResultOfTest', verbose_name='Результаты пройденных тестов'),
        ),
    ]
