# Generated by Django 2.1.7 on 2019-03-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20190319_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultoftest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='administrator.Test', verbose_name='Тест'),
        ),
    ]
