# Generated by Django 2.1.7 on 2019-06-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20190603_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lk_code',
            field=models.CharField(default=0, max_length=60, verbose_name='Код личного кабинета'),
        ),
    ]
