# Generated by Django 2.1.7 on 2019-04-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20190319_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='idNSTU',
            field=models.IntegerField(null=True, verbose_name='id НГТУ'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
