# Generated by Django 2.1.7 on 2020-03-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20190603_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
    ]
