# Generated by Django 2.1.7 on 2019-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_auto_20190418_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер вопроса'),
        ),
        migrations.AddField(
            model_name='test',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=40, verbose_name='Ответ'),
        ),
    ]
