# Generated by Django 2.1.7 on 2020-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='answer',
            field=models.TextField(default='-', verbose_name='Ответ'),
        ),
    ]
