# Generated by Django 2.1.7 on 2020-03-02 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': 'Класс для разметки',
                'verbose_name_plural': 'Классы для разметки',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('answer', models.TextField(verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос для разметки',
                'verbose_name_plural': 'Вопросы для разметки',
            },
        ),
        migrations.CreateModel(
            name='Question_Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_questions', to='markup.Mark', verbose_name='Класс')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_mark', to='markup.Question', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='User_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='markup.Mark', verbose_name='Метка класса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_questions', to='markup.Question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user_question',
            unique_together={('user', 'question')},
        ),
    ]
